apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 5 #This pod ensures 5 pods finish job successfuly
  parallelism: 2 #Two Pods can run parallel
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: nginx:1.22.1
