apiVersion: batch/v1beta1
kind: CronJob
metadata:
name: batch-job
spec:
  schedule: "0,15,30,45 * * * *" #This job runs every 15 minuets every hour every day
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: nginx:1.22.1 # Place your image here
