apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
    name: nginx
spec:
    replicas: 3
    selector:
      matchExpressions: #difference between replication controler and replicaset is the power of selector part in replicaset
        - key: app
          operator: In
          values:
            - nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.22.1
