apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
    name: nginx-daemonset
spec:
  selector:
    matchLabels:
       app: nginx-daemonset
  template:
    metadata:
      labels:
        app: nginx-daemonset
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: main
        image: nginx:1.22.1
